### ISSUE TITLE
WIP Lookup API Device Admin Tool

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/admin-app#130]
Create a simple CRUD tool to manage devices in the Lookup API
https://github.com/topcoder-platform/lookups-api

You should be able to:
 - List devices with basic filtering/search
 - Add a new device
 - Edit a device
 - Soft Delete a device
 - If a device is not attached to anything, it can be destroyed.

**Comment by maxceem** [comment]
@rootelement it looks like Lookup API doesn't support soft-delete of devices. I didn't find any places where it would configure any plugins or code for soft-deleting. See [dynamoose config](https://github.com/topcoder-platform/lookups-api/blob/518207d64d0ef7f557e0dd1d86a9203daab38ef2/src/models/index.js) and [Device model config](https://github.com/topcoder-platform/lookups-api/blob/518207d64d0ef7f557e0dd1d86a9203daab38ef2/src/models/Device.js).

Should we also take care about soft-deleting in Lookups API or did I miss anything?

**Comment by rootelement** [comment]
Build the tool for now without delete. I will work with @callmekatootie to get that implemented.

@callmekatootie can you create an issue for this? We need to be able to remove the devices from the UI, but keep them historically if they've been used. Then also allow them to be destroyed. I think the format should be soft delete on `DELETE /device` and destroy on `DELETE /device?destroy=true` or something like that. I'll leave it up to you.

cc: @cwdcwd

**Comment by callmekatootie** [comment]
Ticket created to support soft deletes in lookup api - https://github.com/topcoder-platform/lookups-api/issues/13. Will get it implemented soon.

**Comment by maxceem** [comment]
This task has been implemented via challenge https://www.topcoder.com/challenges/30117977/?type=develop.

The submission has been pushed to branch https://github.com/topcoder-platform/admin-app/tree/feature/device-management.

**Comment by maxceem** [comment]
![image](https://user-images.githubusercontent.com/146016/77995482-87ad5a00-7334-11ea-9ffa-2ed8bd527e4d.png)

QA guidelines:

The main features implemented:
- List devices with basic filtering/search
- Add a new device
- Edit a device
- Note: deleting is not implemented because the server-side doesn't support it the way we need yet as per https://github.com/topcoder-platform/admin-app/issues/130#issuecomment-593484409.

Additional features:
- when we enter **Type** we show suggestion list with already existent types:

   ![image](https://user-images.githubusercontent.com/146016/77993469-e8d32e80-7330-11ea-91ce-d5ea7e1984d1.png)

- when we enter **Manufacturers** we show a suggestion list with already existent manufacturers for the chosen type.

    ![image](https://user-images.githubusercontent.com/146016/77995344-4cab2680-7334-11ea-9c11-9b75dc5d07da.png)

- when we type in the fields, we should show the list with suggestions but only the ones which include entered string
- we should be able to select any suggestion using mouse or keyboard
- input should allow any value, not only listed in the suggestion list
- we can only show suggestions for the "manufacturer" field if we already entered something to the "type" field

**Comment by rootelement** [comment]
This is a great summary, thanks @maxceem ! I will test in dev a little later today.

**Comment by callmekatootie** [comment]
@rootelement Soft delete feature support is now in lookup api development instance. You can check it out. Let me know when its good to push to master branch

**Comment by rootelement** [comment]
Yes, we can close it.
