### ISSUE TITLE
Terms Admin 2.0 - Manage Users

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/admin-app#153]
We need to make a simple admin tool to be able to search by handle/member id, and view the terms they have signed. And to also possibly sign terms for them (if you're an admin level? power user?)

Using this issue to discuss first.

Here's the existing admin. We should probably use this as a baseline.

## List view
Notice View and Add Members on each term.
![Screen Shot 2020-09-18 at 1 45 06 PM](https://user-images.githubusercontent.com/5400156/93628856-42014e00-f9b5-11ea-9feb-21699c22a7bc.png)

## View Users
![Screen Shot 2020-09-18 at 1 45 33 PM](https://user-images.githubusercontent.com/5400156/93628850-3f9ef400-f9b5-11ea-996b-081c045b2922.png)

## Add User
![Screen Shot 2020-09-18 at 1 46 12 PM](https://user-images.githubusercontent.com/5400156/93628896-59d8d200-f9b5-11ea-9924-1d591db79b96.png)

## Edit Terms
I don't believe we need the Candidate Terms part.
![Screen Shot 2020-09-18 at 1 46 50 PM](https://user-images.githubusercontent.com/5400156/93628937-6d843880-f9b5-11ea-8143-e791fa5a6749.png)

**Comment by maxceem** [comment]
@rootelement 

## List/View/Add Users

1. >We need to make a simple admin tool to be able to search by handle/member id, and view the terms they have signed. 
     And to also possibly sign terms for them

   I suggest to implement it a similar way as it's done for managing `Goups`/`Roles` of users. But currently, we only can search users by `handle` or `email`. Should we add ability to search by `userId` here?

   ![image](https://user-images.githubusercontent.com/146016/93759558-167b9f00-fc13-11ea-926c-b00a50058896.png)

   When clicking the `Terms` item, we can show a dialog, similar what we do for groups/roles:

   ![image](https://user-images.githubusercontent.com/146016/93759698-5c386780-fc13-11ea-96e2-25c6fb8a4b30.png)

2. To `List`/`View`/`Add` members to the Terms, we can use a similar approach as we use for managing members of the `Groups`:

     - `List` terms - on the list page we might add a single link like `manage users` which would lead to the `View` screen. Or we can add 2 links to `view` and to `add` users as in the old admin tool if adding is a frequent operation.
 
    - `View` users of one Terms - same like we do for viewing users of groups:

        ![image](https://user-images.githubusercontent.com/146016/93760743-475cd380-fc15-11ea-92c3-e9c339eb73cc.png)

     - `Add` user to one Terms - when we click `Add Members` button from `View` or `List` screen:

        ![image](https://user-images.githubusercontent.com/146016/93760433-ab32cc80-fc14-11ea-9a3c-5d6eb98df89c.png)

## Edit Terms

It looks like almost everything is implemented related to editing terms. There are 2 possible improvements:

3. Should we show a select list instead of text input for `typeId`?

    In the old admin tool we show `Type` as select:

     ![image](https://user-images.githubusercontent.com/146016/93761396-6a3bb780-fc16-11ea-9035-6905fe474c0e.png)

    While in the new one we are showing row text input:

     ![image](https://user-images.githubusercontent.com/146016/93761487-88091c80-fc16-11ea-865d-0d89c770b7ed.png)

4. Should we add ability to manage Terms dependencies as it's done in the old admin tool? At the moment **Terms Service** doesn't provide API for managing Terms dependencies so we would have to implement it first.

     ![image](https://user-images.githubusercontent.com/146016/93761605-b981e800-fc16-11ea-99fe-dbb3fe03419f.png)

**Comment by rootelement** [comment]
1. Yes, add the ability to search by id
2. This approach is fine.
3. Yes, as in the other issue, we need to add a related table to terms to populate the text for that dropdown.
4. Don't worry about dependencies yet. Leave that out for now.

**Comment by maxceem** [comment]
Done in PR https://github.com/topcoder-platform/admin-app/pull/139

**Comment by rootelement** [comment]
Looks good. Opening a new issue with a couple items, but otherwise good work.
