### ISSUE TITLE
Terms Admin - Issue Creating an NDA

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/admin-app#171]
## Steps to Reproduce
1. Create a new terms
2. Select Type: Contest
3. Select Agreeability Type: Docusign
4. Enter anything in the docusign id field
5. Enter some placeholder text in the body.
6. Save it

If you try to edit that challenge, you'll see there's no docusign id returned. 

It looks like the POST on creating a challenge is not sending the docusignId value from the field. I filled in these values:
![Screen Shot 2020-11-06 at 4 39 01 PM](https://user-images.githubusercontent.com/5400156/98417250-9c7e6880-204e-11eb-96f6-5877520fd611.png)

And this was the POST body from the console:
```json
agreeabilityTypeId: "999a26ad-b334-453c-8425-165d4cf496d7"
created: "2020-11-06T21:37:20.769Z"
createdBy: "jcori"
deletedAt: null
id: "8819a28a-ab08-4394-826c-5a512234aeaa"
legacyId: null
text: "This is test"
title: "Test NDA Again 1"
typeId: 5
updated: null
updatedBy: null
url: null
```
Notice there's no `docusignTemplateId`

**Comment by rootelement** [comment]
Also, after i fixed the terms in the DB and went to edit it, the agreeability type is correct, but it doesn't show the field:
![Screen Shot 2020-11-06 at 4 46 29 PM](https://user-images.githubusercontent.com/5400156/98418551-24fe0880-2051-11eb-9f35-b45e7f331bbc.png)

I assume editing if the field worked wouldn't update that either. The API handles the docusignTemplateId in the POST and PUT requests, so that shouldn't be the problem here:
```javascript
if (termsOfUse.docusignTemplateId) {
    await TermsOfUseDocusignTemplateXref.create({
      termsOfUseId: created.id,
      docusignTemplateId: termsOfUse.docusignTemplateId
    })
  }
```

**Comment by maxceem** [comment]
@rootelement it seems like a Terms API issue, because Admins App sends `docusingTemplateId` in the POST request:

![image](https://user-images.githubusercontent.com/146016/98438098-6f829200-20f0-11eb-8346-7aa34c24f4c3.png)

But Terms API doesn't return it the response:

![image](https://user-images.githubusercontent.com/146016/98438110-85905280-20f0-11eb-9ad2-a9b77b6cc09d.png)

After I'm trying to load created Terms I get an error from API so it's hard to test the second issue with the missing field:

![image](https://user-images.githubusercontent.com/146016/98438135-d607b000-20f0-11eb-811d-d783715ed617.png)

But if I open any existent Terms with correct `docusignTemplateId` (ex: http://local.topcoder-dev.com:3001/#/index/terms/edit/7245bb7d-d7c9-45a0-9603-d5ff05af0977) this field is shown correctly to me:

![image](https://user-images.githubusercontent.com/146016/98438176-3565c000-20f1-11eb-9a6d-b13f30d37dcb.png)

**Comment by maxceem** [comment]
Ah, I've got the second issue https://github.com/topcoder-platform/admin-app/issues/171#issuecomment-723318461.
If it happens to you on PROD but not on DEV, then `AGREE_FOR_DOCUSIGN_TEMPLATE` might be misconfigured on PROD. It should point to the id of **DocueSignable** Aggreability Type in the PROD DB.

**Comment by rootelement** [comment]
Fixed. Thanks!
